# htpasswd -c auth prometheus-dev
# kubectl create secret generic basic-auth --from-file=auth
apiVersion: v1
data:
  auth: YWRtaW4=
kind: Secret
metadata:
  name: basic-auth
  namespace: monitoring
type: Opaque
