- op: add
  path: "/spec/template/spec/volumes/-"
  value:
    name: custom-tools
    emptyDir: {}
- op: add
  path: "/spec/template/spec/initContainers"
  value:
    - name: get-avp
      image: alpine:3.8
      env:
      - name: AVP_VERSION
        value: 1.13.1
      command: [sh, -c]
      args:
        - |
          wget -O argocd-vault-plugin https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64
          chmod +x argocd-vault-plugin
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

- op: add
  path: "/spec/template/spec/containers/0/volumeMounts/-"
  value:
    mountPath: /usr/local/bin/argocd-vault-plugin
    name: custom-tools
    subPath: argocd-vault-plugin
