apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: atlassian/jira-software:9.3.2
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 600
          periodSeconds: 10  
        env:
          - name: ATL_PROXY_NAME
            value: https://lrcsdp.support.cf-cd.com/jira
        resources:
          requests:
            memory: 2Gi
        ports:
          - containerPort: 8080
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-volume
      volumes:
        - name: jira-volume
          emptyDir:
