apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
        - name: jira
          image: atlassian/jira-software:9.3.2
          imagePullPolicy: Always
          env:
            - name: ATL_PROXY_NAME
              value: https://lrcsdp.support.cf-cd.com/jira
          resources:
            requests:
              memory: 2Gi
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: /var/atlassian/application-data/jira
            name: jira-volume
      volumes:
        - name: jira-volume
          emptyDir:
