apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
  labels:
    app: jira
data:
  JVM_MINIMUM_MEMORY: 2048m
  JVM_MAXIMUM_MEMORY: 2048m
  ATL_PROXY_NAME: jira.support.cf-cd.com
  ATL_PROXY_PORT: '32631'
  PGDATA: /var/lib/postgresql/data/pgdata
