apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
namePrefix: prod-
resources:
- ../../base
patchesStrategicMerge:
- version.yml
images:
- name: lrochette/gitops-simple-app
  newTag: 7.0-prod
