# Default values for color.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

nodeSelector:
  kubernetes.io/os: linux # specify the OS your step should run on
  kubernetes.io/arch: amd64
