apiVersion: v1
kind: Service
metadata:
  labels:
    app: globex
  name: globex
  namespace: csdp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: globex
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: globex
  name: globex
  namespace: csdp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: globex
  template:
    metadata:
      labels:
        app: globex
    spec:
      containers:
      - image: lrochette/globex:1.6.55
        imagePullPolicy: Always
        name: globex
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: globex
  namespace: csdp
spec:
  ingressClassName: nginx
  rules:
  - host: lrcsdp.support.cf-cd.com
    http:
      paths:
      - backend:
          service:
            name: globex
            port:
              number: 80
        path: /globex
        pathType: ImplementationSpecific
