apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color
  namespace: csdp
  labels:
    app: color
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://9EFB8399DE9A817EC221411CDCB1620C.gr7.us-east-1.eks.amazonaws.com
  project: prod
  source:
    path: ./kustomize/color/overlays/prod
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
