apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex-prod
  namespace: csdp
  labels:
    app: globex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: prod
  source:
    path: ./kustomize/globex/overlays/prod
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
