apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-prod
  namespace: csdp
  annotations:
    argocd-image-updater.argoproj.io/image-list: prod=lrochette/gitops-simple-app
    argocd-image-updater.argoproj.io/prod.update-strategy: latest
    argocd-image-updater.argoproj.io/prod.allow-tags: regexp:-prod$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization

spec:
  project: prod

  source:
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
    path: ./kustomize/image-updater/overlays/prod/

  destination:
    name: lr3
    namespace: prod

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
