apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-prod
  namespace: csdp
  annotations:
    argocd-image-updater.argoproj.io/image-list: example=docker.io/lrochette/gitops-simple-app
    argocd-image-updater.argoproj.io/example.update-strategy: latest
    argocd-image-updater.argoproj.io/example.allow-tags: regexp:-prod$
spec:
  project: prod

  source:
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: HEAD
    path: ./kustomize/image-updater/overlays/prod/

  destination:
    server: lr3
    namespace: prod

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
