apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/lrochette/gitops-cert-level-2-examples:~1
spec:
  project: default

  source:
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: HEAD
    path: ./kustomize/image-updater/image-updater/overlays/dev/

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
