{{- $fullName := include "color.fullname" . -}}
{{- $svcPort := .Values.service.port -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/app-root: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: lrcsdp.support.cf-cd.com
      http:
        paths:
          - path: /color-{{ .Release.Name }}
            pathType: Prefix
            backend:
              service:
                name: color-{{ .Release.Name }}
                port:
                  number: {{ $svcPort }} 
