kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: prod/secret
  labels:
    owner: laurent.rochette
type: Opaque
stringData:
  sample-secret: <foo>
