apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      nodeSelector:
        kubernetes.io/os: linux    # specify the OS your step should run on
        kubernetes.io/arch: amd64
      containers:
      - image: lrochette/color:blue
        name: app2
        ports:
        - containerPort: 80
