apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bad-image
  name: bad-image
spec:
  revisionHistoryLimit: 1
  replicas: 2
  selector:
    matchLabels:
      app: bad-image
  template:
    metadata:
      labels:
        app: bad-image
    spec:
      nodeSelector:
        kubernetes.io/os: linux # specify the OS your step should run on
        kubernetes.io/arch: amd64
      containers:
        - name: bad-image
          image: lrochette/color:red
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
