apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rollout.yaml
- services.yaml
- gateway.yaml    ## Istio Virtual Service (and Gateway)
- success-rate.yaml            ## Analysis Template for Rollouts
- skywalking.yaml            ## Analysis Template for Rollouts
