apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: route-patch.json
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1
resources:
- ns.yaml
- appProject.yaml
- cronworkflow.yaml
- github.com/codefresh-io/csdp-official/csdp/hybrid/basic/apps/argo-workflows?ref=0.1.26
