apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name:  {{ template "jenkins.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: jenkins
