apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s"  .Release.Name .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: JENKINS_USERNAME
              value: {{ default "test" .Values.jenkins.jenkinsUsername | quote }}
          ports:
            - name: http
              containerPort: 8080
