apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: {{ .Release.Name }}-{{ .Chart.Name}}
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30080
  selector:
    app: jenkins
