apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: default
spec:
  revisionHistoryLimit: 1
  replicas: 10
  strategy:
    canary:
      canaryService: argo-rollouts-canary-service # our created canary service
      stableService: argo-rollouts-stable-service # our created stable service
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: argo-rollouts-http-route # our created httproute
            namespace: default
      steps:
        - setWeight: 20
        - pause: {duration: 30}
        - setWeight: 40
        - pause: {duration: 30}
        - setWeight: 60
        - pause: {duration: 30}
        - setWeight: 80
        - pause: {duration: 30}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: gke-rollout
  template:
    metadata:
      labels:
        app: gke-rollout
    spec:
      containers:
        - name: rollouts-demo
          # image: kostiscodefresh/summer-of-k8s-app:v1
          image: kostiscodefresh/summer-of-k8s-app:v2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
