apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      annotations:
        buildID: "{{ .Values.buildID }}"
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      nodeSelector:
        kubernetes.io/os: linux    # specify the OS your step should run on
        kubernetes.io/arch: amd64
      containers:
      - name: {{ .Chart.Name }}
      {{- if .Values.global }}
        image: "{{ .Values.image.repository }}:{{ .Values.global.image.tags.ctrlr }}"
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
