kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: prod/secret
  labels:
    owner: laurent
    date: Feb-9_8-53
type: Opaque
stringData:
  sample-secret: <foo>
