kind: Secret
apiVersion: v1
metadata:
  name: jenkins
  annotations:
    avp.kubernetes.io/path: jenkins/secrets
  labels:
    app.kubernetes.io/instance: aws-secret
    owner: laurent
type: Opaque
stringData:
  jk-password: <pwd>
