apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}

data:
  {{- if empty .Values.accessKey }}
  access-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  access-key: {{ .Values.accessKey | b64enc | quote }}
  {{- end }}
  {{- if empty .Values.secretKey }}
  secret-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  secret-key: {{ .Values.secretKey | b64enc | quote }}
  {{- end }}
