apiVersion: v2
name: dev
description: A Helm chart for Kubernetes
type: application
version: 0.1.29
dependencies:
  - name: buslog
    version: "1.4.2"
    repository: "https://h.cfcr.io/codefreshdemo/public"
  - name: ctrlr
    version: "1.3.3"
    repository: "https://h.cfcr.io/codefreshdemo/public"
  - name: flask-ui
    version: "1.2.6"
    repository: "https://h.cfcr.io/codefreshdemo/public"
