apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: pass-always
spec:
  metrics:
  - name: pass-5
    count: 5
    interval: 5s
    failureLimit: 1
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:3.8
                command: [sh, -c]
                args: [exit 0]
              restartPolicy: Never
          backoffLimit: 0
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  labels:
    app: bad-canary
  name: fail-always
  namespace: dev
spec:
  metrics:
  - count: 5
    failureLimit: 1
    interval: 5s
    name: fail-1
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - args:
                - exit 1
                command:
                - sh
                - -c
                image: alpine:3.8
                name: sleep
              restartPolicy: Never
