apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bad-bg
  labels:
    app: bad-bg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev # temporarily set to Runtime namespace, CR-10565
    name: in-cluster
  project: dev
  source:
    path: ./manifests/bad-bg/

    repoURL: https://github.com/lrochette/csdp_applications.git
      # https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    automated:
      prune: true
