apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bad-app
  namespace: csdp
  labels:
    app: bad-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/bad-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/bad-app
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
