apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/app-group: training
spec:
  project: default
  source:
    path: ./simple-app
    repoURL: https://github.com/codefresh-contrib/gitops-certification-examples/
    targetRevision: main
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
