apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] > 0.90
    provider:
      prometheus:
       # address: http://prometheus-operator-prometheus.prometheus-operator:9090
        # address: http://prometheus-operator.prometheus:9090
        address: http://lrcsdp.support.cf-cd.com:9090/prometheus
        query: >+
          sum(
            rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status!~"[4-5].*"}[20s]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[20s])
          )
