apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: ./manifests/jenkins-aws-secret/
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_TYPE
          value: awssecretsmanager
        - name: AWS_REGION
          value: us-east-1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
