apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readiness-app
  namespace: csdp
  labels:
    app: readiness
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/readiness
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: ./manifests/readiness
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
