apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: color-dev
  namespace: csdp
  labels:
    app: color
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: ./kustomize/color/overlays/dev
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
