apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-secret
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: .external-secrets/ExternalSecret
    repoURL: https://github.com/lrochette/argocd-micro-example-apps.git
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

aws secretsmanager create-secret \
  --name secret/demo-secrets-2 --region us-east-1 \
  --secret-string '{"tokenA":"not_enough_secrests"},{"tokenB":"too_many_secrets"}'
