apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secret
spec:
  project: dev
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/vitorpavani/argocd-vault-plugin
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
