apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-analysis
  namespace: csdp
  labels:
    app: canary-analysis
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /kustomize/analysis
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: ./kustomize/analysis/
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
