apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret
spec:
  project: dev
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
    helm:
      releaseName: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
