apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-helmfile
  namespace: csdp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # repoURL: https://gitlab.com/voting-application/config.git
    repoUrl: https://github.com/lrochette/voting-application-helmfile.git
    targetRevision: main
    path: helm
    plugin:
      name: helmfile
      env:
      - name: HELM_DATA_HOME
        value: /home/argocd/.local/share/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
