apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secure-set
spec:
  generators:
  - git:
      repoURL: https://github.com/lrochette/csdp_applications.git
      revision: HEAD
      files:
      - path: "appset/**/config.json"
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: security # project is restricted
      source:
        targetRevision: "{{app.revision}}"
        path: "{{app.subfolder}}"
        repoURL: "{{app.src}}"
      destination:
        name: in-cluster # cluster is restricted
        namespace: other # namespace is restricted
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
