apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secure-set
spec:
  generators:
  - git:
      repoURL: https://github.com/lrochette/csdp_applications.git
      revision: HEAD
      files:
      - path: "appset/**/config.json"
  template:
    spec:
      project: security # project is restricted
      source:
        # developers may customize app details using JSON files from above repo URL
        repoURL: '{{source}}'
        targetRevision: {{revision}}
        path: {{path}}
      destination:
        name: in-cluster # cluster is restricted
        namespace: other # namespace is restricted
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
