apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./deploy/helm/apps
    repoURL: https://github.com/andrewmetcalfbede/csdptest.git
    targetRevision: HEAD
    helm:
      values: |-
        app:
          name: appname
        ingress:
          host: some.host
        db:
          name: some_name
          host: some_host
      valueFiles:
      valueFiles:
        - values-bede-devopsdashboard-api.yaml
        - values.yaml
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
