apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-demo
  namespace: csdp
  labels:
    app: canary-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    # path: ./examples/canary/
    path: ./examples/analysis/
    repoURL: https://github.com/lrochette/rollouts-demo.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: true
