apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globex-dev
  namespace: dev
  labels:
    app: globex
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    name: in-cluster
  project: dev
  source:
    path: ./kustomize/globex/overlays/dev
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - createNamespace=true
    automated:
      prune: true
      selfHeal: false
