apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-dev
  namespace: csdp
  annotations:
    argocd-image-updater.argoproj.io/image-list: example=docker.io/lrochette/gitops-simple-app
    argocd-image-updater.argoproj.io/example.update-strategy: latest
    argocd-image-updater.argoproj.io/example.allow-tags: regexp:-dev$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization

spec:
  project: dev

  source:
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: main
    path: ./kustomize/image-updater/overlays/dev/

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
