apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: helm/minio
    repoURL: https://github.com/lrochette/csdp_applications.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: minio
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
