apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: myapp
    # argocd.argoproj.io/instance: argocd
    # chart: raw-0.2.5
    # heritage: Helm
    # release: argocd-apps
  name: code-01
  namespace: csdp
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: dev
  source:
    path: ./code-01/helm/helmfile/myapp
    repoURL: https://github.com/rootleveltech/codefresh-helmfile-webinar

    # plugin:
      # env:
      # - name: CLUSTER_ID
      #   value: primary
      # - name: HELMFILE_GLOBAL_OPTIONS
      #   value: --file helmfile.d/applications/argocd/
      # - name: HELMFILE_TEMPLATE_OPTIONS
      #   value: --include-crds
      # - name: HELM_TEMPLATE_OPTIONS
      #   value: --skip-tests
      # name: helmfile.yaml
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
