apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmfile-hosted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lrochette/voting-application-helmfile.git
    targetRevision: main
    path: helm
    plugin:
      name: helmfile
      env:
      - name: HELM_DATA_HOME
        value: /home/argocd/.local/share/helm
  destination:
    name: lr2
    namespace: dev
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
