apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bad-canary
  labels:
    app: bad-canary
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifests/bad-canary
    codefresh.io/app-group: training
spec:
  destination:
    namespace: dev # temporarily set to Runtime namespace, CR-10565
    name: in-cluster
  project: dev
  source:
    path: ./manifests/bad-canary/

    repoURL: https://github.com/lrochette/csdp_applications.git
      # https://github.com/lrochette/csdp_applications.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    automated:
      prune: true
