apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      containers:
      - env:
        - name: MYSQL_PWD
          value: password
        image: mysql:8
        name: mysql
