apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
resources:
- ../../base
patchesStrategicMerge:
- version.yml
images:
- name: lrochette/gitops-simple-app
  newTag: 5.0-dev
