apiVersion: v1
kind: Service
metadata:
  labels:
    app: color
  name: color
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080     
  selector:
    app: color
  type: ClusterIP
