apiVersion: v1
kind: Service
metadata:
  labels:
    app: color
  name: color
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    app: color
  type: LoadBalancer
