apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      nodeSelector:
        kubernetes.io/os: linux    # specify the OS your step should run on
        kubernetes.io/arch: amd64
      containers:
      - image: lrochette/color:yellow
        name: app1
        ports:
        - containerPort: 80
